sourceId: 11
database: CDM_IBM_ccae_v1151

exportPath: "export_ccae"

connectionDetails:
  dbms: pdw
  server: JRDUSAPSCTL01
  port: 17001

securePassword: True

resultSchema: "scratch.dbo"
referenceSchema: "scratch.dbo"
cdmSchema: "CDM_IBM_ccae_v1151.dbo"
vocabularySchema: "Vocabulary_20200525.dbo"
drugEraSchema: "CDM_IBM_ccae_v1151.reward"

tables:
  outcomeCohort: "rb_ccae_v1151_outcome_cohort"
  cohort: "rb_ccae_v1151_cohort"
  sccResult: "rb_ccae_v1151_scc_result"
