sourceId: 11
database: truven_ccae
name: "IBM CCAE"

exportPath: "export_ccae"
referencePath: "reference_files"

connectionDetails:
  extraSettings: "ssl=true&sslfactory=com.amazon.redshift.ssl.NonValidatingFactory"
  dbms: redshift
  server: ohda-prod-1.cldcoxyrkflo.us-east-1.redshift.amazonaws.com/truven_ccae
  port: 5439
  user: jgilber2

useSecurePassword: True
passwordEnvironmentVariable: "REDSHIFT_DB_PASSWORD"
keyringService: "rhealth-db"
useMppBulkLoad: True

resultSchema: "scratch_jgilber2"
referenceSchema: "scratch_jgilber2"
cdmSchema: "cdm_truven_ccae_v1479"
vocabularySchema: "cdm_truven_ccae_v1479"
drugEraSchema: "scratch_jgilber2"
cdmVersionTable: "_version"

tables:
  outcomeCohort: "rb_outcome_cohort_feb_2021"
  cohort: "rb_cohort_feb_2021"
  sccResult: "rb_scc_result_feb_2021"
  # Reference table definitions
  cohortDefinition: "rb_cohort_definition_feb_2021"
  outcomeCohortDefinition: "rb_outcome_cohort_definition_feb_2021"
  conceptSetDefinition: "rb_concept_set_definition_feb_2021"
  atlasOutcomeReference: "rb_atlas_outcome_reference_feb_2021"
  atlasOutcomeConcept: "rb_atlas_outcome_concept_feb_2021"
  atlasExposureReference: "rb_atlas_exposure_reference_feb_2021"
  atlasExposureConcept: "rb_atlas_exposure_concept_feb_2021"
  customExposure: "rb_custom_exposure_feb_2021"
  customExposureConcept: "rb_custom_exposure_concept_feb_2021"
  analysisSetting: "rb_analysis_setting_feb_2021"
