sourceId: 13
database: CDM_IBM_MDCR_v1152

exportPath: "export_mcdr"
referencePath: "reference_files"m

connectionDetails:
  extraSettings: "ssl=true&sslfactory=com.amazon.redshift.ssl.NonValidatingFactory"
  dbms: redshift
  server: rhealth-prod-1.cldcoxyrkflo.us-east-1.redshift.amazonaws.com/truven_mdcr
  port: 5439
  user: jgilber2

useSecurePassword: True
passwordEnvironmentVariable: "REDSHIFT_DB_PASSWORD"
useMppBulkLoad: True

resultSchema: "scratch_rewardb_mcdc"
referenceSchema: "scratch_rewardb_mcdc"
cdmSchema: "cdm"
vocabularySchema: "cdm"
drugEraSchema: "scratch_rewardb_mcdc"

tables:
  outcomeCohort: "rb_outcome_cohort"
  cohort: "rb_cohort"
  sccResult: "rb_scc_result"
  # Reference table definitions
  cohortDefinition: "rb_cohort_definition"
  outcomeCohortDefinition: "rb_outcome_cohort_definition"
  conceptSetDefinition: "rb_concept_set_definition"
  atlasOutcomeReference: "rb_atlas_outcome_reference"
  atlasConceptReference: "rb_atlas_concept_reference"
  customExposure: "rb_custom_exposure"
  customExposureConcept: "rb_custom_exposure_concept"
  analysisSetting: "rb_analysis_setting"

