sourceId: 12
database: truven_mdcd
name: "IBM MDCD"

exportPath: "export_mcdc"
referencePath: "reference_files"

connectionDetails:
  extraSettings: "ssl=true&sslfactory=com.amazon.redshift.ssl.NonValidatingFactory"
  dbms: redshift
  server: rhealth-prod-1.cldcoxyrkflo.us-east-1.redshift.amazonaws.com/truven_mdcd
  port: 5439
  user: jgilber2

useSecurePassword: True
keyringService: "rhealth-db"
passwordEnvironmentVariable: "REDSHIFT_DB_PASSWORD"
bulkUpload: True

resultSchema: "scratch_reward_mdcd_feb2021"
referenceSchema: "scratch_reward_mdcd_feb2021"
cdmSchema: "cdm"
vocabularySchema: "cdm"
drugEraSchema: "scratch_reward_mdcd_feb2021"
cdmVersionTable: "_version"

tables:
  outcomeCohort: "rb_outcome_cohort"
  cohort: "rb_cohort"
  sccResult: "rb_scc_result"
  # Reference table definitions
  cohortDefinition: "rb_cohort_definition"
  outcomeCohortDefinition: "rb_outcome_cohort_definition"
  conceptSetDefinition: "rb_concept_set_definition"
  atlasOutcomeReference: "rb_atlas_outcome_reference"
  atlasOutcomeConcept: "rb_atlas_outcome_concept"
  atlasExposureReference: "rb_atlas_exposure_reference"
  atlasExposureConcept: "rb_atlas_exposure_concept"
  customExposure: "rb_custom_exposure"
  customExposureConcept: "rb_custom_exposure_concept"
  analysisSetting: "rb_analysis_setting"

