sourceId: 10
database: optum_extended_ses
name: "Optum"

exportPath: "export_optum_ses"
referencePath: "reference_files"

connectionDetails:
  extraSettings: "ssl=true&sslfactory=com.amazon.redshift.ssl.NonValidatingFactory"
  dbms: redshift
  server: rhealth-prod-3.cldcoxyrkflo.us-east-1.redshift.amazonaws.com/optum_extended_ses
  port: 5439
  user: jgilber2

useSecurePassword: True
keyringService: "rhealth-db"
passwordEnvironmentVariable: "REDSHIFT_DB_PASSWORD"
useMppBulkLoad: True

resultSchema: "scratch_reward_optum_ses"
referenceSchema: "scratch_reward_optum_ses"
cdmSchema: "cdm"
vocabularySchema: "cdm"
drugEraSchema: "scratch_reward_optum_ses"
cdmVersionTable: "_version"
cdmVersion: "v5.3.1"

tables:
  outcomeCohort: "rb_outcome_cohort_feb2021"
  cohort: "rb_cohort_feb2021"
  sccResult: "rb_scc_result_feb2021"
  # Reference table definitions
  cohortDefinition: "rb_cohort_definition_feb2021"
  outcomeCohortDefinition: "rb_outcome_cohort_definition_feb2021"
  conceptSetDefinition: "rb_concept_set_definition_feb2021"
  atlasOutcomeReference: "rb_atlas_outcome_reference_feb2021"
  atlasOutcomeConcept: "rb_atlas_outcome_concept_feb2021"
  atlasExposureReference: "rb_atlas_exposure_reference_feb2021"
  atlasExposureConcept: "rb_atlas_exposure_concept_feb2021"
  customExposure: "rb_custom_exposure_feb2021"
  customExposureConcept: "rb_custom_exposure_concept_feb2021"
  analysisSetting: "rb_analysis_setting_feb2021"
