name: development dashboard outcomes
short_name: dev_outcomes
description: Example description text
outcome_concept_ids: [312437]
custom_outcome_cohort_ids: [11643] # These will not be multiplied by 100
target_concept_ids: ~
development_db: false

connectionDetails:
  dbms: sqlite
  server: development_outcomes.db

resultsDatabase:
  schema: "scratch.dbo"
  cohortDefinitionTable: "homer_cohort_definition_May2020"
  outcomeCohortDefinitionTable: "homer_outcome_cohort_definition_May2020"
  asurvResultsTable: "homer_AllbyAll_results_May2020"

  cdmDataSource:
    dbms: pdw
    server: JRDUSAPSCTL01
    port: 17001
