name: development dashboard
short_name: dev
description: Example description text
outcome_concept_ids: ~
custom_outcome_cohort_ids: ~ # These will not be multiplied by 100
target_concept_ids: [739138]
development_db: true
connectionDetails:
  dbms: sqlite
  server: development.db

resultsDatabase:
  schema: "scratch.dbo"
  cohortDefinitionTable: "homer_cohort_definition_May2020"
  outcomeCohortDefinitionTable: "homer_outcome_cohort_definition_May2020"
  asurvResultsTable: "homer_AllbyAll_results_May2020"

  cdmDataSource:
    dbms: pdw
    server: JRDUSAPSCTL01
    port: 17001
