name: 'anti-TNF exposures'
short_name: tnfi
description: 'Dashboard for all outcomes for anti-TNF exposures'
outcome_concept_ids: ~
custom_outcome_cohort_ids: [7542, 7551, 7552, 7553, 7576, 7543, 7545, 7546, 7507, 7547, 7548, 7549, 7550, 7822, 7823, 10357,11073, 2538, 10593, 10605, 15078, 10607, 11643]
target_concept_ids: [40161532, 1593700, 912263, 45892883, 21603907, 35603563, 1151789, 1119119, 19041065, 937368, 35200139, 1592513, 1511348]
connectionDetails:
  dbms: "postgresql"
  server: "reward.cterqq54xyuu.us-east-1.rds.amazonaws.com/rewardb_dev"
  port: 5432
  user: "reward_admin"
  password: ""

resultsDatabase:
  schema: "scratch.dbo"
  cohortDefinitionTable: "homer_cohort_definition_May2020"
  outcomeCohortDefinitionTable: "homer_outcome_cohort_definition_May2020"
  asurvResultsTable: "homer_AllbyAll_results_May2020"
  cdmDataSource:
    dbms: pdw
    server: JRDUSAPSCTL01
    port: 17001

negative_control_outcome_list: 'extra/negative_controls/anti_tnfi_full_atlas.csv'
