name: 'Develop'
short_name: dev_nc_test
description: 'Development dashboard - schema is not safe'
outcome_concept_ids: ~
custom_outcome_cohort_ids: ~
target_concept_ids: [937368, 19041065, 1151789, 912263, 1119119, 21603907]

connectionDetails:
  dbms: "postgresql"
  server: "reward.cterqq54xyuu.us-east-1.rds.amazonaws.com/rewardb_dev"
  port: 5432
  user: "reward_admin"

resultsDatabase:
  schema: "scratch.dbo"
  vocabularySchema: "Vocabulary_20200525.dbo"
  cohortDefinitionTable: "homer_cohort_definition_May2020"
  outcomeCohortDefinitionTable: "homer_outcome_cohort_definition_May2020"
  asurvResultsTable: "homer_AllbyAll_results_May2020"
  cemSchema: "CEM_V2_0_0_20200226.dbo"
  negativeControlTable: "matrix_summary"
  atlasCohorts: "rewardb_atlas_cohort_reference"
  atlasConceptMapping: "rewardb_atlas_concept_reference"

  cdmDataSource:
    dbms: pdw
    server: JRDUSAPSCTL01
    port: 17001

negative_control_outcome_list: 'extra/negative_controls/anti_tnfi_full_atlas.csv'
