name: 'Famotidine outcomes'
short_name: famotidine
description: 'Dashboard for all outcomes for famotidine and comparator exposures'
outcome_concept_ids: ~
custom_outcome_cohort_ids: ~
target_concept_ids: [1149196, 953076, 961047, 923645, 21600081, 21600095, 21600109]
connectionDetails:
  dbms: "postgresql"
  server: "reward.cterqq54xyuu.us-east-1.rds.amazonaws.com/rewardb_dev"
  port: 5432
  user: "reward_admin"
  password: ""

resultsDatabase:
  schema: "scratch.dbo"
  vocabularySchema: "Vocabulary_20200525.dbo"
  cohortDefinitionTable: "homer_cohort_definition_May2020"
  outcomeCohortDefinitionTable: "homer_outcome_cohort_definition_May2020"
  asurvResultsTable: "homer_AllbyAll_results_May2020"
  cemSchema: "CEM_V2_0_0_20200226.dbo"
  negativeControlTable: "matrix_summary"
  atlasCohorts: "rewardb_atlas_cohort"

  cdmDataSource:
    dbms: pdw
    server: JRDUSAPSCTL01
    port: 17001

