name: development dashboard outcomes
short_name: dev_outcomes
description: Example description text
outcome_concept_ids: [312437]
custom_outcome_cohort_ids: [11643] # These will not be multiplied by 100
target_concept_ids: ~

connectionDetails:
  dbms: "postgresql"
  server: "reward.cterqq54xyuu.us-east-1.rds.amazonaws.com/rewardb_dev"
  port: 5432
  user: "reward_admin"
  password: ""

resultsDatabase:
  schema: "scratch.dbo"
  cohortDefinitionTable: "homer_cohort_definition_May2020"
  outcomeCohortDefinitionTable: "homer_outcome_cohort_definition_May2020"
  asurvResultsTable: "homer_AllbyAll_results_May2020"
  cemSchema: "CEM_V2_0_0_20200226.dbo"
  negativeControlTable: "matrix_summary"

  cdmDataSource:
    dbms: pdw
    server: JRDUSAPSCTL01
    port: 17001
