webApiUrl: "https://epi.jnj.com:8443/WebAPI"
# These will be automatically included on any database rebuild. Other cohorts can still be added manually later
maintinedAtlasCohortList: [7542, 7551, 7552, 7553, 7576, 7543, 7545, 7546, 7507, 7547, 7548, 7549, 7550, 7822, 7823, 10357, 11073, 2538, 10593, 10605, 15078, 10607, 11643, 12047, 14615, 13719, 10977]

resultsTablePrefix: reward_results_dev

cdmDatabase:
  schema: "scratch.jgilber2"
  vocabularySchema: "Vocabulary_20200525.dbo"
  cemSchema: "CEM_V2_0_0_20200226.dbo"
  cohortDefinitionTable: "rewardb_cohort_definition_aug2020"
  outcomeCohortDefinitionTable: "rewardb_outcome_cohort_definition_aug2020"
  conceptSetDefinitionTable: "rewardb_conceptset_definition_aug2020"
  mergedResultsTable: "rewardb_results_aug2020"
  atlasCohortReferenceTable: "rewardb_atlas_cohort_reference_aug2020"
  atlasConceptReferenceTable: "rewardb_atlas_concept_reference_aug2020"

cdmDataSource:
  dbms: pdw
  server: JRDUSAPSCTL01
  port: 17001

dataSources:
  Optum SES_1292:
    sourceId: 10
    database: "CDM_Optum_Extended_SES_v1292"
    cdmDatabaseSchema: "CDM_Optum_Extended_SES_v1292.dbo"
    drugEraSchema: "CDM_Optum_Extended_SES_v1292.reward"
    cohortTable: "cohort_optum_v1292"
    outcomeCohortTable: "outcome_cohort_optum_v1292"
    outcomeSummaryTable: "outcome_summary_optum_v1292"

  CCAE_1247:
    sourceId: 11
    database: "CDM_IBM_ccae_v1247"
    cdmDatabaseSchema: "CDM_IBM_ccae_v1247.dbo" #this is where we'll pull drug and condition history for patients
    drugEraSchema: "CDM_IBM_ccae_v1247.reward"
    cohortTable: "cohort_ccae_v1247" # will be created and saved on scratch.dbo
    outcomeCohortTable: "outcome_cohort_ccae_v1247" # will be created and saved on scratch.dbo
    outcomeSummaryTable: "outcome_summary_ccae_v1247" # will be created and saved on scratch.dbo

  MDCD_1259:
    sourceId: 12
    database: "CDM_IBM_MDCD_v1259"
    cdmDatabaseSchema: "CDM_IBM_MDCD_v1259.dbo"
    drugEraSchema: "CDM_IBM_MDCD_v1259.reward"
    cohortTable: "cohort_mdcd_v1259"
    outcomeCohortTable: "outcome_cohort_mdcd_v1259"
    outcomeSummaryTable: "outcome_summary_mdcd_v1259"

  MDCR_1297:
    sourceId: 13
    database: "CDM_IBM_MDCR_v1297"
    cdmDatabaseSchema: "CDM_IBM_MDCR_v1297.dbo"
    drugEraSchema: "CDM_IBM_MDCR_v1297.reward"
    cohortTable: "cohort_mdcr_v1297"
    outcomeCohortTable: "outcome_cohort_mdcr_v1297"
    outcomeSummaryTable: "outcome_summary_mdcr_v1297"
