webApiUrl: "https://epi.jnj.com:8443/WebAPI"
testMode: false
resultsTablePrefix: reward_results_dev
exportPath: "export"

connectionDetails:
  dbms: "postgresql"
  server: "reward.cterqq54xyuu.us-east-1.rds.amazonaws.com/rewardb_dev"
  port: 5432
  user: "reward_admin"
  password: "p87rhW#Vs2fF"

rewardbResultsSchema: "rewardb_2020_Nov_12"
vocabularySchema: "vocabulary"
cemSchema: "cem"
