webApiUrl: "https://epi.jnj.com:8443/WebAPI"
exportPath: "export"

connectionDetails:
  dbms: "postgresql"
  server: "reward.cterqq54xyuu.us-east-1.rds.amazonaws.com/rewardb_dev"
  port: 5432
  user: "reward_admin"

rewardbResultsSchema: "rewardb_july_2021"
vocabularySchema: "vocabulary"
cemSchema: "cem"

cacheDir: "/Users/jamie/PycharmProjects/REWARD_B_dashboard/app-cache"

keyringService: "reward-db"

cemConnectionDetails:
  apiUrl: http://cem.ohdsi.org:8080
