library(rewardb)
config <- loadGlobalConfiguration("config/global-cfg.yml")
exportReferenceTables(config, exportPath = "rewardb-references.zip")

rstudioapi::jobRunScript("scripts/runFullAnalysisMdcd.R", name = "MDCD - reward full set", workingDir = ".")
rstudioapi::jobRunScript("scripts/runFullAnalysisMdcr.R", name = "MDCR - reward full set", workingDir = ".")
rstudioapi::jobRunScript("scripts/runFullAnalysisJmdc.R", name = "JMDC - reward full set", workingDir = ".")
rstudioapi::jobRunScript("scripts/runFullAnalysisOptum.R", name = "Optum - reward full set", workingDir = ".")
rstudioapi::jobRunScript("scripts/runFullAnalysisCcae.R", name = "CCAE - reward full set", workingDir = ".")
rstudioapi::jobRunScript("scripts/runFullAnalysisPharmetics.R", name = "Pharmetrics - reward full set", workingDir = ".")